# Generated by Django 3.2 on 2021-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('schema', models.CharField(max_length=128)),
                ('tenant_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
