# Generated by Django 3.2 on 2021-06-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('schema', models.CharField(max_length=128)),
                ('domain', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
