# Generated by Django 3.2 on 2021-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
