# Generated by Django 3.2 on 2021-06-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_tenant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='domain',
        ),
    ]
