# Generated by Django 3.2 on 2021-06-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AlterField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
